### ISSUE TITLE
WARN BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS

### ISSUE THREAD

**Issue by romanceline** [EU-ECDC/epitweetr#12] opened 2021-02-15 23:41 UTC
Dear Epitweetr team,

Epitweetr has been working fine on my computer for a couple of weeks, i have tweets collected, geotagged and aggregated until the 25th of January. Since then, tweets are still collected but there seems to be an issue in the geotagging. 
When i run the detect_loop, i'm having this message:
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
2021-02-16 00:34:02[INFO]---->geolocating tweets for 2021.01.27.00001
21/02/16 00:34:50 WARN BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS

Thanks in advance for your help!

**Comment by forchard** [comment] 2021-02-16 07:43
Hello!
The warning you are seeing is not an error. Is just saying that an optimization library can not be load. This is the standard behavior unless you set it up and it has no impact on epitweetr. Please see the [spark documentation](https://spark.apache.org/docs/latest/ml-guide.html#dependencies)

So if epitweetr stop working the issue is probably elsewhere. Can you provide more details on what the unexpected behavior is? Is epitweetr hanging after that warning?

Best,
Francisco

**Comment by lauespinosa** [comment] 2021-03-06 13:32
Dear @romanceline , 

Are you still having issues in geotagging the collected tweets?

Please, let us know if you see any error in the configuration page under 'Detection pipeline' or in the windows running the detection loop.

Best,

Laura

**Comment by romanceline** [comment] 2021-03-06 20:41
Dear Laura, Francisco,

So sorry for not replying earlier, I still have the same issue.
Everything i see in the 'tweets/search' folder goes up until today, same in the 'series' folder.
The folder 'tweets/geolocated' is stuck in January. 
In the app, everything is green in the troubleshoot tab.
Here are the messages i see in the detection pipeline:

3	geotag	aborted	2021-01-25 06:36:41	2021-02-16 11:29:07	2021-01-25 21:51:24	Max number of retries reached processing
4	aggregate	scheduled	2021-03-06 21:38:43	2021-02-15 21:57:48	2021-01-25 06:34:48	Max number of retries reached serie country_counts for 2021-01-16

Best,

Celine

**Comment by lauespinosa** [comment] 2021-03-07 16:50
Dear Celine,

Thank you for sending this additional information. Unfortunately, I cannot properly assess the issue since the message in the detection pipeline is not the complete error message.

First, please try clicking on 'Run geotag' in the configuration page. 

If you still get an error or aborted task, please open the file **detect.log** (usually saved under `C:/users/your_username/epitweetr`) and copy the last lines you see with the error message(s). 
When sending the message(s), **please consider anonymising any reference to your directory or folder, for data privacy** (for example, if there is a path `C:/users/jane_doe/epitweetr`, you should replace it with `C:/users/name_surname/epitweetr`.

Best,

Laura

**Comment by lauespinosa** [comment] 2021-04-09 17:41
Dear @romanceline ,

Other users have reported issues with winutils URL included in epitweetr that affected geonames and languages, and subsequently aggregation process.

We have released a new version in CRAN (0.1.28) with a new winutils URL.

You can try to install the new version of `epitweetr` and click on 'Run dependencies', 'Run geonames' and 'Run languages' in case this solves your issue.

**Comment by lauespinosa** [comment] 2021-06-13 19:24
Dear @romanceline,

Another epitweetr user had similar issues. The issues were solved by downloading the latest version of epitweetr from CRAN and launching epitweetr in a new folder.

Please try this and keep me updated 😃

**Comment by romanceline** [comment] 2021-06-14 13:09
Many thanks @lauespinosa, I will try and let you know.
In case this works, do you know if it will be possible to repatriate all tweets collected so far in the old folder into the new one?

**Comment by romanceline** [comment] 2021-06-14 22:28
It seems I have now an issue on the step 'run languages' as it gets aborted.
I get the following message:

`Max number of retries reached failed while indexing languages Error in spark_job(paste("updateLanguages", conf_geonames_as_arg(), conf_languages_as_arg(), : Error encountered while exeuting: java -cp "C:/Users/user/Documents/R/R-4.0.3/library/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;C:/Users/user/Desktop/R/Scripts/TweeterData/jars/*" -Xmx4g org.ecdc.twitter.Tweets updateLanguages geonamesSource "C:/Users/user/Desktop/R/Scripts/TweeterData/geo/allCountries.txt" geonamesDestination "C:/Users/user/Desktop/R/Scripts/TweeterData/geo" geonamesSimplify "TRUE" langCodes "en,fr,es,pt" langNames "English,French,Spanish,Portuguese" langPaths "C:/Users/user/Desktop/R/Scripts/TweeterData/languages/en.txt.gz,C:/Users/user/Desktop/R/Scripts/TweeterData/languages/fr.txt.gz,C:/Users/user/Desktop/R/Scripts/TweeterData/languages/es.txt.gz,C:/Users/user/Desktop/R/Scripts/TweeterData/languages/pt.txt.gz" langIndexPath "C:/Users/user/Desktop/R/Scripts/TweeterData/geo/lang_vectors.index" parallelism 2`

**Comment by lauespinosa** [comment] 2021-12-22 13:59
Hi @romanceline ,

This issue may appear because you need to download first the default languages (English, French, Spanish and Portuguese) and only after that, you can add or delete languages.

Please try the following:
- Open the epitweetr Shiny app
- Go to configuration page and ensure the four languages are in the list. If you deleted or added additional languages, you can change it by selecting the language in the drop down menu and clicking on '+' or '-' as needed.
- Click on 'run languages'
- Wait for the four default languages to be downloaded
- Add or delete languages as needed

Please let us know if this solves the problem and we can close the issue

**Comment by lauespinosa** [comment] 2022-04-05 08:28
issue closed since no more feedback was provided by user

**Closed by lauespinosa** 2022-04-05 08:28 UTC
Labels: bug
