### ISSUE TITLE
Error with geonames

### ISSUE THREAD

**Issue by ines219** [EU-ECDC/epitweetr#30] opened 2021-07-11 23:35 UTC
When I ran the epitweetr app for the first time and ran geonames, I get this error where it seems it can only partially download the associated geonames file:

![image](https://user-images.githubusercontent.com/30426753/125212992-178dd200-e2f4-11eb-8209-cddeeb0f650f.png)
![image](https://user-images.githubusercontent.com/30426753/125212976-05139880-e2f4-11eb-9861-800b17799773.png)

However, I seem to be able to directly download this file without any issues:
![image](https://user-images.githubusercontent.com/30426753/125213027-3f7d3580-e2f4-11eb-8def-54b8e7af7ada.png)

Do you happen to know any fixes for this? Otherwise, is it possible to give the Epitweetr app my download of the geonames file directly?

Thanks

**Comment by stonehc** [comment] 2021-07-28 06:22
I am also recieving the same error and was also able to download the allCountries.zip. 
<img width="275" alt="Screen Shot 2021-07-28 at 4 18 31 PM" src="https://user-images.githubusercontent.com/78945701/127273880-89e08738-ed1d-44a2-b563-a753f8a266fe.png">

**Comment by forchard** [comment] 2021-07-28 10:27
Hi! It seems that this error is coming from the R native function from downloading files/
Can you try to reproduce the error  by opening a new R session and writing
> download.file("http://download.geonames.org/export/dump/allCountries.zip", "test.zip") 

Best,
Francisco

**Comment by stonehc** [comment] 2021-07-29 01:21
This is the error that occured when I ran that line.

**Comment by forchard** [comment] 2021-07-29 06:21
Hi  stonehc,
I do not see any error message on your last post...
Best,
Francisco

**Comment by stonehc** [comment] 2021-07-29 07:17
<img width="746" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/78945701/127448649-fb0a4aa5-394b-416f-9670-1b2845bb6a19.png">
Apologies. I am unsure why it did not attach.

**Comment by forchard** [comment] 2021-07-29 07:33
Thanks!
Is the download failing after 60 seconds? If so cay you try to execute the following code before the download?
options(timeout=120)

**Comment by lauespinosa** [comment] 2021-12-22 13:55
@ines219 , @stonehc , please let us know if the problem was solved and we can close the issue

**Comment by lauespinosa** [comment] 2022-04-05 08:29
issue closed since no more feedback was provided by user

**Closed by lauespinosa** 2022-04-05 08:29 UTC
Labels: bug

**Comment by rzaha** [comment] 2022-07-21 20:58
Hi Laura,
i am Rana Elzahar the focal person of Epitweer in EMRO region WHO
i suffer from the above error while trying to install i tried all the above solution but nothing new 
can you please help.
trying to have fransisco email as well 
waiting for your reply
